// SCOREBOARD - start //

class scoreboard;
  
  mailbox #(transaction) mbx;
  
  transaction tr;
  
  event next;
  
  bit [7:0] din[$];  // queue for storing data_in generated by generator
  bit [7:0] temp;
  
  function new(mailbox #(transaction) mbx);
    
    this.mbx = mbx;
    
  endfunction
  
  task run();
    
    forever begin
      
      mbx.get(tr);
      
      tr.display("SCB");
      
      if(tr.wr == 1'b1) begin
        din.push_front(tr.data_in);
        $display("SCB : Data Stored in QUEUE : %0d", tr.data_in);
      end
      
      if(tr.rd == 1'b1) begin
        
        if(tr.empty == 1'b0) begin
          temp = din.pop_back();
          
          if(tr.data_out == temp) begin
            $display("SCB : Data is as expected");
          end
          
          else begin
            $display("SCB : Data is not as expected");
          end
          
        end
        
        else begin
          $display("SCB : FIFO is empty");
        end
        
      end
      ->next;
    end
    
  endtask
  
endclass

// SCOREBOARD - end   //